"""
Módulo de DTOs da aplicação.
"""

from src.application.dto.user_dto import (
    AlterarSenhaRequest,
    AtualizarUsuarioRequest,
    ConfirmarEmailRequest,
    ConfirmarTelefoneRequest,
    EsqueciSenhaRequest,
    LoginRequest,
    MensagemResponse,
    UsuarioResponse,
    RegistroRequest,
    RedefinirSenhaRequest,
    RefreshTokenRequest,
    RefreshTokenResponse,
    TokenResponse,
    PaginatedResponse,
    ConfiguracaoPlanoResponse,
)
from src.application.dto.bot_dto import (
    AtualizarBotRequest,
    AtualizarCatalogoRequest,
    BotResponse,
    CatalogoItemRequest,
    CatalogoItemResponse,
    CatalogoResponse,
    ConfigurarTelegramRequest,
    ConfigurarWhatsAppRequest,
    CriarBotRequest,
    EstatisticasBotResponse,
    LLMConfigResponse,
    ListaBotsResponse,
    QRCodeResponse,
    StatusConexaoResponse,
    TestarBotRequest,
    TesteBotResponse,
    TelegramConfigResponse,
    WhatsAppConfigResponse,
    WorkingHoursResponse,
)
from src.application.dto.conversation_dto import (
    AtribuirAtendenteRequest,
    ContextoConversaResponse,
    ConversaResponse,
    DadosClienteResponse,
    EnviarMensagemRequest,
    ListaConversasResponse,
    ListaMensagensResponse,
    MensagemResponse,
    MetadataMidiaResponse,
)

__all__ = [
    # User DTOs
    "RegistroRequest",
    "LoginRequest",
    "ConfirmarEmailRequest",
    "ConfirmarTelefoneRequest",
    "EsqueciSenhaRequest",
    "RedefinirSenhaRequest",
    "RefreshTokenRequest",
    "AtualizarUsuarioRequest",
    "AlterarSenhaRequest",
    "UsuarioResponse",
    "TokenResponse",
    "RefreshTokenResponse",
    "MensagemResponse",
    "PaginatedResponse",
    "ConfiguracaoPlanoResponse",
    # Bot DTOs
    "CriarBotRequest",
    "AtualizarBotRequest",
    "ConfigurarWhatsAppRequest",
    "ConfigurarTelegramRequest",
    "TestarBotRequest",
    "CatalogoItemRequest",
    "AtualizarCatalogoRequest",
    "BotResponse",
    "ListaBotsResponse",
    "QRCodeResponse",
    "StatusConexaoResponse",
    "TesteBotResponse",
    "WorkingHoursResponse",
    "LLMConfigResponse",
    "CatalogoItemResponse",
    "CatalogoResponse",
    "EstatisticasBotResponse",
    "WhatsAppConfigResponse",
    "TelegramConfigResponse",
    # Conversation DTOs
    "AtribuirAtendenteRequest",
    "EnviarMensagemRequest",
    "ConversaResponse",
    "ListaConversasResponse",
    "DadosClienteResponse",
    "ContextoConversaResponse",
    "MensagemResponse",
    "ListaMensagensResponse",
    "MetadataMidiaResponse",
]
